services:
  rails_api:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - mariadb
      - redis
    volumes:
      - .:/rails
      - ruby-bundle-cache:/bundle
    links:
      - mariadb

  mariadb:
    restart: on-failure
    image: mariadb:11.5
    env_file: .env
    volumes:
      - "/var/lib/mysql/data:${MARIADB_DATA_DIR}"
      - "/var/lib/mysql/logs:${MARIADB_LOG_DIR}"
      - /var/docker/mariadb/conf:/etc/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        # environment:
        # MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        # MYSQL_DATABASE: "${MYSQL_DATABASE}"
        # MYSQL_USER: "${MYSQL_USER}"
        # MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  redis:
    restart: on-failure
    image: "redis:7.4-alpine"
    ports:
      - 6379
    volumes:
      - ./tmp/redis_data:/var/lib/redis/data

volumes:
  ruby-bundle-cache:
    external: true
